### ISSUE TITLE
Code is running without waiting for get request. 

### ISSUE THREAD

**Issue by atawfique21** [atawfique21/Word-Sprint#3]
**Describe your issue/question/bug**
I'm trying to fill an array using a Get request and the code should not be running before the get request is fulfilled, but is still running. 
**To Reproduce**
1. Open Console on index.html 
2. You'll see that "Hi" is printing before the get request is filled, even though Hi is at the end of the document. 
**Expected behavior**
Get Request should run before anything else.

**Comment by DZGoldman** [comment]
are you using async / await?

**Comment by atawfique21** [comment]
> are you using async / await?

Yes!

**Comment by DZGoldman** [comment]
The call to `getRandomWord` needs its own `await`; you can just give your `window.onload` function an `async`
