### ISSUE TITLE
QuerySelectorAll doesn't seem to be clearing out and is leaving old nodes in history.

### ISSUE THREAD

**Issue by atawfique21** [atawfique21/Word-Sprint#4]
**Describe your issue/question/bug**
I've tracked down my issue but don't know how to fix it. Essentially, I'm Queryselecting all of the letters of my word so I can apply CSS/logic to each letter at a time. But when a word is done and a new word appears, it seems that QuerySelecting again (even if it's now for a new query selector argument like moving from char1 to char2), it keeps char1 in history and is constantly trying to apply CSS to it even though it can't anymore. I've tried to solve this in a few ways, such as dynamically changing the queryselector for each word, but again, it's keeping the old nodes in history. 
 
**To Reproduce**
1. Go to index.html
2. Open console.
3. Type in the first word, you'll see that everything works (including backspaces) 
4. New word will appear and you will see that we are console.logging node list twice. And through that, we can see that there are essentially two node lists there. 

**Expected behavior**
No errors should appear in console. 
**Error Message - If Applicable**
`Uncaught TypeError: Cannot read property 'classList' of undefined at HTMLBodyElement.<anonymous> (apicall.js:59)`
**Three Links to Resources You Used to Try and Fix the Bug**
1. https://blog.teamtreehouse.com/manipulating-classes-using-classlist-api
2. https://stackoverflow.com/questions/50673431/javascript-cannot-read-property-classlist-of-undefined-error
3. https://stackoverflow.com/questions/14809528/why-does-js-code-var-a-document-queryselectoradata-a-1-cause-error

**Comment by atawfique21** [comment]
At this point, I'm not sure if the issue even relates to removing the nodes from history because I've added code that removes the node children. Even though I've taken that extra precaution, the error is still apparent.

**Comment by DZGoldman** [comment]
Okay, that was my guess (i.e., adding new nodes but not removing the old ones)
